[build-system]
requires = [
    "setuptools",
    "cython>=0.25,<3.0",
    "murmurhash>=1.0.2,<1.1.0",
    "cymem>=2.0.2,<2.1.0",
    "preshed>=3.0.2,<3.1.0",
    "blis>=0.7.8,<0.8.0",
    "numpy>=1.15.0",
]
build-backend = "setuptools.build_meta"
